env:
  es2020: true
  node: true
extends:
  - standard
  - 'plugin:@typescript-eslint/recommended'
  - prettier
  - 'prettier/@typescript-eslint'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  semi: [error, always]
  'prettier/prettier': warn
